version: "3"
services:
  node:
    container_name: r_s_node
    build:
      context: "./docker/node"
      dockerfile: "Dockerfile"
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 6006:6006
    tty: true
    volumes:
      - .:/app
    networks:
      - r_s2_node

networks:
  r_s2_node:
    driver: "bridge"
