version: "3"
services:
  node:
    container_name: r_s_node
    build:
      context: "./docker/node"
      dockerfile: "Dockerfile"
    ports:
      - 3000:3000
      - 3002:3002
      - 6006:6006
    tty: true
    volumes:
      - .:/app
    networks:
      - r_s2_node
    depends_on:
      - mongo

  mongo:
    container_name: r_s_mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    networks:
      - r_s2_node

networks:
  r_s2_node:
    driver: "bridge"
